./main_prefill \
--template_filename_axmodel "llm-jp-3-1.8b-instruct3-AX620E/llama_p128_l%d_together.axmodel" \
--axmodel_num 24 \
--tokenizer_type 2 \
--filename_tokenizer_model "http://localhost:8080" \
--bos 0 --eos 0 \
--filename_post_axmodel "llm-jp-3-1.8b-instruct3-AX620E/llama_post.axmodel" \
--filename_tokens_embed "llm-jp-3-1.8b-instruct3-AX620E/model.embed_tokens.weight.bfloat16.bin" \
--tokens_embed_num 99584 \
--tokens_embed_size 2048 \
--use_mmap_load_embed 1 \
--live_print 1 \
--continue 1 \
--prompt "$1"
